In [1]:
import time

notebook_start_time = time.time()

# Set up environment

In [2]:
import sys
from pathlib import Path


def is_google_colab() -> bool:
    if "google.colab" in str(get_ipython()):
        return True
    return False


def clone_repository() -> None:
    !git clone https://github.com/decodingml/hands-on-recommender-system.git
    %cd hands-on-recommender-system/


def install_dependencies() -> None:
    !pip install --upgrade uv
    !uv pip install --all-extras --system --requirement pyproject.toml


if is_google_colab():
    clone_repository()
    install_dependencies()

    root_dir = str(Path().absolute())
    print("⛳️ Google Colab environment")
else:
    root_dir = str(Path().absolute().parent)
    print("⛳️ Local environment")

# Add the root directory to the `PYTHONPATH` to use the `recsys` Python module from the notebook.
if root_dir not in sys.path:
    print(f"Adding the following directory to the PYTHONPATH: {root_dir}")
    sys.path.append(root_dir)

⛳️ Local environment
Adding the following directory to the PYTHONPATH: c:\Users\SUNIL KUMAR\Downloads\krish_naik\personalized-recommender-course

# 👩🏻‍🔬 Feature pipeline: Computing features

## Imports

In [3]:
%load_ext autoreload
%autoreload 2
# pip install polars sentence-transformers loguru
import warnings
from pprint import pprint

!pip install polars tensorflow torch
%pip install polars sentence-transformers loguru pydantic tensorflow torch
import polars as pl
import torch
from loguru import logger
from sentence_transformers import SentenceTransformer

warnings.filterwarnings("ignore")

from recsys import hopsworks_integration
from recsys.config import settings
from recsys.features.articles import (
    compute_features_articles,
    generate_embeddings_for_dataframe,
)
from recsys.features.customers import DatasetSampler, compute_features_customers
from recsys.features.interaction import generate_interaction_data
from recsys.features.ranking import compute_ranking_dataset
from recsys.features.transactions import compute_features_transactions
from recsys.hopsworks_integration import feature_store
from recsys.raw_data_sources import h_and_m as h_and_m_raw_data

Requirement already satisfied: polars in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (1.41.2)
Requirement already satisfied: tensorflow in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (2.21.0)
Requirement already satisfied: torch in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (2.12.0)
Requirement already satisfied: polars-runtime-32==1.41.2 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from polars) (1.41.2)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (7.35.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.33.0)
Requirement already satisfied: setuptools in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.4.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: filelock in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.25.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from torch) (2026.3.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (13.1.0)
Requirement already satisfied: namex in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\sunil kumar\appdata\local\programs\python\python311\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
c:\Users\SUNIL KUMAR\Downloads\krish_naik\personalized-recommender-course\.venv\Scripts\python.exe: No module named pip

Note: you may need to restart the kernel to use updated packages.

c:\Users\SUNIL KUMAR\Downloads\krish_naik\personalized-recommender-course\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Constants

These are the default settings used across the lessons. You can always override them in the `.env` file that sits at the root of the repository:

In [4]:
pprint(dict(settings))

{'CUSTOMER_DATA_SIZE': <CustomerDatasetSize.SMALL: 'SMALL'>,
 'CUSTOM_HOPSWORKS_INFERENCE_ENV': 'custom_env_name',
 'FEATURES_EMBEDDING_MODEL_ID': 'all-MiniLM-L6-v2',
 'HOPSWORKS_API_KEY': SecretStr('**********'),
 'HOPSWORKS_HOST': 'c.app.hopsworks.ai',
 'HOPSWORKS_PROJECT_NAME': 'hm_recommender',
 'OPENAI_API_KEY': SecretStr('**********'),
 'OPENAI_MODEL_ID': 'gpt-4o-mini',
 'RANKING_DATASET_VALIDATON_SPLIT_SIZE': 0.1,
 'RANKING_EARLY_STOPPING_ROUNDS': 5,
 'RANKING_ITERATIONS': 100,
 'RANKING_LEARNING_RATE': 0.2,
 'RANKING_MODEL_TYPE': 'ranking',
 'RANKING_SCALE_POS_WEIGHT': 10,
 'RECSYS_DIR': WindowsPath('c:/Users/SUNIL KUMAR/Downloads/krish_naik/personalized-recommender-course/recsys'),
 'TWO_TOWER_DATASET_TEST_SPLIT_SIZE': 0.1,
 'TWO_TOWER_DATASET_VALIDATON_SPLIT_SIZE': 0.1,
 'TWO_TOWER_LEARNING_RATE': 0.01,
 'TWO_TOWER_MODEL_BATCH_SIZE': 2048,
 'TWO_TOWER_MODEL_EMBEDDING_SIZE': 16,
 'TWO_TOWER_NUM_EPOCHS': 10,
 'TWO_TOWER_WEIGHT_DECAY': 0.001}

The most important one is the dataset size.

Choosing a different dataset size will impact the time it takes to run everything and the quality of the final models. We suggest using a small dataset size when running this the first time.

Suported user dataset sizes:

In [5]:
DatasetSampler.get_supported_sizes()

{<CustomerDatasetSize.LARGE: 'LARGE'>: 50000,
 <CustomerDatasetSize.MEDIUM: 'MEDIUM'>: 5000,
 <CustomerDatasetSize.SMALL: 'SMALL'>: 1000}

## <span style="color:#ff5f27">🔮 Connect to Hopsworks Feature Store </span>

In [6]:
project, fs = hopsworks_integration.get_feature_store()

2026-05-31 20:27:14.409 | INFO     | recsys.hopsworks_integration.feature_store:get_feature_store:13 - Loging to Hopsworks using HOPSWORKS_API_KEY env var.

2026-05-31 20:27:14,411 INFO: Initializing external client
2026-05-31 20:27:14,411 INFO: Base URL: https://eu-west.cloud.hopsworks.ai:443

2026-05-31 20:27:16,946 INFO: Python Engine initialized.

Logged in to project, explore it here https://eu-west.cloud.hopsworks.ai:443/p/33047

# The H&M dataset

To show how a recommender system using the two tower architecture works, we will use the [H&M Personalized Fashion Recommendations](https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations) dataset.

It consists of:
- articles
- customers
- transactions

# 🗄️ Articles data

The **article_id** and **product_code** serve different purposes in the context of H&M's product database:

- **Article ID**: This is a unique identifier assigned to each individual article within the database. It is typically used for internal tracking and management purposes. Each distinct item or variant of a product (e.g., different sizes or colors) would have its own unique article_id.

- **Product Code**: This is also a unique identifier, but it is associated with a specific product or style rather than individual articles. It represents a broader category or type of product within H&M's inventory. Multiple articles may share the same product code if they belong to the same product line or style.

While both are unique identifiers, the article_id is specific to individual items, whereas the product_code represents a broader category or style of product.

Here is an example:

**Product: Basic T-Shirt**

- **Product Code:** TS001

- **Article IDs:**
    - Article ID: 1001 (Size: Small, Color: White)
    - Article ID: 1002 (Size: Medium, Color: White)
    - Article ID: 1003 (Size: Large, Color: White)
    - Article ID: 1004 (Size: Small, Color: Black)
    - Article ID: 1005 (Size: Medium, Color: Black)

In this example, "TS001" is the product code for the basic t-shirt style. Each variant of this t-shirt (e.g., different sizes and colors) has its own unique article_id.

In [7]:
articles_df = h_and_m_raw_data.extract_articles_df()
articles_df.shape

(105542, 25)

The articles DataFrame looks as follows:

In [8]:
articles_df.head(3)

shape: (3, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ article_i ┆ product_c ┆ prod_name ┆ product_t ┆ … ┆ section_n ┆ garment_g ┆ garment_g ┆ detail_d │
│ d         ┆ ode       ┆ ---       ┆ ype_no    ┆   ┆ ame       ┆ roup_no   ┆ roup_name ┆ esc      │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆           ┆ i64       ┆   ┆ str       ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 108775015 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Womens    ┆ 1002      ┆ Jersey    ┆ Jersey   │
│           ┆           ┆           ┆           ┆   ┆ Everyday  ┆           ┆ Basic     ┆ top with │
│           ┆           ┆           ┆           ┆   ┆ Basics    ┆           ┆           ┆ narrow   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shoulde… │
│ 108775044 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Womens    ┆ 1002      ┆ Jersey    ┆ Jersey   │
│           ┆           ┆           ┆           ┆   ┆ Everyday  ┆           ┆ Basic     ┆ top with │
│           ┆           ┆           ┆           ┆   ┆ Basics    ┆           ┆           ┆ narrow   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shoulde… │
│ 108775051 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Womens    ┆ 1002      ┆ Jersey    ┆ Jersey   │
│           ┆           ┆ (1)       ┆           ┆   ┆ Everyday  ┆           ┆ Basic     ┆ top with │
│           ┆           ┆           ┆           ┆   ┆ Basics    ┆           ┆           ┆ narrow   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shoulde… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Check for NaNs:

In [9]:
articles_df.null_count()

shape: (1, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ article_i ┆ product_c ┆ prod_name ┆ product_t ┆ … ┆ section_n ┆ garment_g ┆ garment_g ┆ detail_d │
│ d         ┆ ode       ┆ ---       ┆ ype_no    ┆   ┆ ame       ┆ roup_no   ┆ roup_name ┆ esc      │
│ ---       ┆ ---       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 416      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Articles feature engineering

In [10]:
articles_df = compute_features_articles(articles_df)
articles_df.shape

(105542, 27)

The features of the articles look as:

In [11]:
articles_df.head(3)

shape: (3, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ article_i ┆ product_c ┆ prod_name ┆ product_t ┆ … ┆ garment_g ┆ prod_name ┆ article_d ┆ image_ur │
│ d         ┆ ode       ┆ ---       ┆ ype_no    ┆   ┆ roup_name ┆ _length   ┆ escriptio ┆ l        │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ n         ┆ ---      │
│ str       ┆ i64       ┆           ┆ i64       ┆   ┆ str       ┆ u32       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 108775015 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Jersey    ┆ 9         ┆ Strap top ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ Basic     ┆           ┆ - Vest    ┆ repo.hop │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ top in    ┆ s.works/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Garmen…   ┆ dev/jd…  │
│ 108775044 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Jersey    ┆ 9         ┆ Strap top ┆ https:// │
│           ┆           ┆           ┆           ┆   ┆ Basic     ┆           ┆ - Vest    ┆ repo.hop │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ top in    ┆ s.works/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Garmen…   ┆ dev/jd…  │
│ 108775051 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Jersey    ┆ 13        ┆ Strap top ┆ https:// │
│           ┆           ┆ (1)       ┆           ┆   ┆ Basic     ┆           ┆ (1) -     ┆ repo.hop │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Vest top  ┆ s.works/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in Ga…    ┆ dev/jd…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Create embeddings from the articles description

In [12]:
for i, desc in enumerate(articles_df["article_description"].head(n=3)):
    logger.info(f"Item {i+1}:\n{desc}")

2026-05-31 20:29:02.897 | INFO     | __main__:<module>:2 - Item 1:
Strap top - Vest top in Garment Upper body
Appearance: Solid
Color: Dark Black (Black)
Category: Ladieswear - Womens Everyday Basics - Jersey Basic
Details: Jersey top with narrow shoulder straps.
2026-05-31 20:29:02.906 | INFO     | __main__:<module>:2 - Item 2:
Strap top - Vest top in Garment Upper body
Appearance: Solid
Color: Light White (White)
Category: Ladieswear - Womens Everyday Basics - Jersey Basic
Details: Jersey top with narrow shoulder straps.
2026-05-31 20:29:02.906 | INFO     | __main__:<module>:2 - Item 3:
Strap top (1) - Vest top in Garment Upper body
Appearance: Stripe
Color: Dusty Light White (Off White)
Category: Ladieswear - Womens Everyday Basics - Jersey Basic
Details: Jersey top with narrow shoulder straps.

In [13]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
logger.info(
    f"Loading '{settings.FEATURES_EMBEDDING_MODEL_ID}' embedding model to {device=}"
)

# Load the embedding model from SentenceTransformer's model registry.
model = SentenceTransformer(settings.FEATURES_EMBEDDING_MODEL_ID, device=device)

2026-05-31 20:29:03.742 | INFO     | __main__:<module>:8 - Loading 'all-MiniLM-L6-v2' embedding model to device='cpu'

2026-05-31 20:29:03,742 INFO: Load pretrained SentenceTransformer: all-MiniLM-L6-v2

In [14]:
articles_df = generate_embeddings_for_dataframe(
    articles_df, "article_description", model, batch_size=128
)  # Reduce batch size if getting OOM errors.

Generating embeddings: 100%|██████████| 105542/105542 [59:55<00:00, 29.35it/s]

For each article description, we have a numerical vector which we can feed to a model, opposite to a string containing the description of an object.

In [15]:
articles_df[["article_description", "embeddings"]].head(3)

shape: (3, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ article_description             ┆ embeddings                      │
│ ---                             ┆ ---                             │
│ str                             ┆ list[f64]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Strap top - Vest top in Garmen… ┆ [-0.026782, 0.082344, … 0.0227… │
│ Strap top - Vest top in Garmen… ┆ [-0.010396, 0.089874, … 0.0225… │
│ Strap top (1) - Vest top in Ga… ┆ [-0.032753, 0.091124, … 0.0228… │
└─────────────────────────────────┴─────────────────────────────────┘

### Looking at image links

In [16]:
articles_df["image_url"][0]

'https://repo.hops.works/dev/jdowling/h-and-m/images/010/0108775015.jpg'

In [17]:
from IPython.display import HTML, display

image_urls = articles_df["image_url"].tail(12).to_list()
grid_html = '<div style="display: grid; grid-template-columns: repeat(6, 1fr); gap: 10px; max-width: 900px;">'

for url in image_urls:
    grid_html += f'<img src="{url}" style="width: 100%; height: auto;">'

grid_html += "</div>"

display(HTML(grid_html))

## Customers Data

In [19]:
customers_df = h_and_m_raw_data.extract_customers_df()
customers_df.shape

(1371980, 7)

The customers DataFrame looks as follows:

In [20]:
customers_df.head(3)

shape: (3, 7)
┌───────────────────┬──────┬────────┬──────────────────┬──────────────────┬─────┬──────────────────┐
│ customer_id       ┆ FN   ┆ Active ┆ club_member_stat ┆ fashion_news_fre ┆ age ┆ postal_code      │
│ ---               ┆ ---  ┆ ---    ┆ us               ┆ quency           ┆ --- ┆ ---              │
│ str               ┆ f64  ┆ f64    ┆ ---              ┆ ---              ┆ i64 ┆ str              │
│                   ┆      ┆        ┆ str              ┆ str              ┆     ┆                  │
╞═══════════════════╪══════╪════════╪══════════════════╪══════════════════╪═════╪══════════════════╡
│ 00000dbacae5abe5e ┆ null ┆ null   ┆ ACTIVE           ┆ NONE             ┆ 49  ┆ 52043ee2162cf5aa │
│ 23885899a1fa4…    ┆      ┆        ┆                  ┆                  ┆     ┆ 7ee79974281641…  │
│ 0000423b00ade9141 ┆ null ┆ null   ┆ ACTIVE           ┆ NONE             ┆ 25  ┆ 2973abc54daa8a5f │
│ 8cceaf3b26c6a…    ┆      ┆        ┆                  ┆                  ┆     ┆ 8ccfe9362140c6…  │
│ 000058a12d5b43e67 ┆ null ┆ null   ┆ ACTIVE           ┆ NONE             ┆ 24  ┆ 64f17e6a330a8579 │
│ d225668fa1f8d…    ┆      ┆        ┆                  ┆                  ┆     ┆ 8e4998f62d0930…  │
└───────────────────┴──────┴────────┴──────────────────┴──────────────────┴─────┴──────────────────┘

Check for NaNs:

In [21]:

customers_df.null_count()

shape: (1, 7)
┌─────────────┬────────┬────────┬────────────────────┬───────────────────────┬───────┬─────────────┐
│ customer_id ┆ FN     ┆ Active ┆ club_member_status ┆ fashion_news_frequenc ┆ age   ┆ postal_code │
│ ---         ┆ ---    ┆ ---    ┆ ---                ┆ y                     ┆ ---   ┆ ---         │
│ u32         ┆ u32    ┆ u32    ┆ u32                ┆ ---                   ┆ u32   ┆ u32         │
│             ┆        ┆        ┆                    ┆ u32                   ┆       ┆             │
╞═════════════╪════════╪════════╪════════════════════╪═══════════════════════╪═══════╪═════════════╡
│ 0           ┆ 895050 ┆ 907576 ┆ 6062               ┆ 16009                 ┆ 15861 ┆ 0           │
└─────────────┴────────┴────────┴────────────────────┴───────────────────────┴───────┴─────────────┘

## Customers feature engineering

In [22]:
customers_df = compute_features_customers(customers_df, drop_null_age=True)
customers_df.shape

(1356119, 5)

The features of the customers DataFrame looks as follows:

In [23]:
customers_df.head(3)

shape: (3, 5)
┌─────────────────────────────┬────────────────────┬──────┬────────────────────────────┬───────────┐
│ customer_id                 ┆ club_member_status ┆ age  ┆ postal_code                ┆ age_group │
│ ---                         ┆ ---                ┆ ---  ┆ ---                        ┆ ---       │
│ str                         ┆ str                ┆ f64  ┆ str                        ┆ str       │
╞═════════════════════════════╪════════════════════╪══════╪════════════════════════════╪═══════════╡
│ 00000dbacae5abe5e23885899a1 ┆ ACTIVE             ┆ 49.0 ┆ 52043ee2162cf5aa7ee7997428 ┆ 46-55     │
│ fa4…                        ┆                    ┆      ┆ 1641…                      ┆           │
│ 0000423b00ade91418cceaf3b26 ┆ ACTIVE             ┆ 25.0 ┆ 2973abc54daa8a5f8ccfe93621 ┆ 19-25     │
│ c6a…                        ┆                    ┆      ┆ 40c6…                      ┆           │
│ 000058a12d5b43e67d225668fa1 ┆ ACTIVE             ┆ 24.0 ┆ 64f17e6a330a85798e4998f62d ┆ 19-25     │
│ f8d…                        ┆                    ┆      ┆ 0930…                      ┆           │
└─────────────────────────────┴────────────────────┴──────┴────────────────────────────┴───────────┘


# Transactions Data

In [25]:
transactions_df = h_and_m_raw_data.extract_transactions_df()
transactions_df.shape

(31788324, 5)

The transaction DataFrame looks as follows:

In [26]:
transactions_df.head(3)

shape: (3, 5)
┌────────────┬─────────────────────────────────┬────────────┬──────────┬──────────────────┐
│ t_dat      ┆ customer_id                     ┆ article_id ┆ price    ┆ sales_channel_id │
│ ---        ┆ ---                             ┆ ---        ┆ ---      ┆ ---              │
│ date       ┆ str                             ┆ i64        ┆ f64      ┆ i64              │
╞════════════╪═════════════════════════════════╪════════════╪══════════╪══════════════════╡
│ 2018-09-20 ┆ 000058a12d5b43e67d225668fa1f8d… ┆ 663713001  ┆ 0.050831 ┆ 2                │
│ 2018-09-20 ┆ 000058a12d5b43e67d225668fa1f8d… ┆ 541518023  ┆ 0.030492 ┆ 2                │
│ 2018-09-20 ┆ 00007d2de826758b65a93dd24ce629… ┆ 505221004  ┆ 0.015237 ┆ 2                │
└────────────┴─────────────────────────────────┴────────────┴──────────┴──────────────────┘

## Transactions feature engineering

In [27]:
transactions_df = compute_features_transactions(transactions_df)
transactions_df.shape

(31788324, 9)

The time of the year a purchase was made should be a strong predictor, as seasonality plays a big factor in fashion purchases. Here, you will use the month of the purchase as a feature. Since this is a cyclical feature (January is as close to December as it is to February), you'll map each month to the unit circle using sine and cosine.

Thus, the features of the transactions DataFrame look as follows:

In [28]:
transactions_df.head(3)

shape: (3, 9)
┌───────┬───────────────────────────┬────────────┬──────────┬───┬──────┬───────┬─────┬─────────────┐
│ t_dat ┆ customer_id               ┆ article_id ┆ price    ┆ … ┆ year ┆ month ┆ day ┆ day_of_week │
│ ---   ┆ ---                       ┆ ---        ┆ ---      ┆   ┆ ---  ┆ ---   ┆ --- ┆ ---         │
│ i64   ┆ str                       ┆ str        ┆ f64      ┆   ┆ i32  ┆ i8    ┆ i8  ┆ i8          │
╞═══════╪═══════════════════════════╪════════════╪══════════╪═══╪══════╪═══════╪═════╪═════════════╡
│ 0     ┆ 000058a12d5b43e67d225668f ┆ 663713001  ┆ 0.050831 ┆ … ┆ 2018 ┆ 9     ┆ 20  ┆ 4           │
│       ┆ a1f8d…                    ┆            ┆          ┆   ┆      ┆       ┆     ┆             │
│ 0     ┆ 000058a12d5b43e67d225668f ┆ 541518023  ┆ 0.030492 ┆ … ┆ 2018 ┆ 9     ┆ 20  ┆ 4           │
│       ┆ a1f8d…                    ┆            ┆          ┆   ┆      ┆       ┆     ┆             │
│ 0     ┆ 00007d2de826758b65a93dd24 ┆ 505221004  ┆ 0.015237 ┆ … ┆ 2018 ┆ 9     ┆ 20  ┆ 4           │
│       ┆ ce629…                    ┆            ┆          ┆   ┆      ┆       ┆     ┆             │
└───────┴───────────────────────────┴────────────┴──────────┴───┴──────┴───────┴─────┴─────────────┘

We don't want to work with ~30 million transactions in these series, as everything will take too much time to run. Thus, we create a subset of the original dataset by randomly sampling from the customers' datasets and taking only their transactions.

In [29]:
sampler = DatasetSampler(size=settings.CUSTOMER_DATA_SIZE)
dataset_subset = sampler.sample(
    customers_df=customers_df, transations_df=transactions_df
)
customers_df = dataset_subset["customers"]
transactions_df = dataset_subset["transactions"]

2026-05-31 23:49:48.835 | INFO     | recsys.features.customers:sample:29 - Sampling 1000 customers.
2026-05-31 23:49:49.221 | INFO     | recsys.features.customers:sample:32 - Number of transactions for all the customers: 31788324
2026-05-31 23:49:51.245 | INFO     | recsys.features.customers:sample:38 - Number of transactions for the 1000 sampled customers: 23799

In [30]:
transactions_df.shape

(23799, 9)

Some of the remaining customers:

In [31]:
for customer_id in transactions_df["customer_id"].unique().head(10):
    logger.info(f"Logging customer ID: {customer_id}")

2026-05-31 23:50:14.324 | INFO     | __main__:<module>:2 - Logging customer ID: 24f4a093ca23af340534c48077d95a509c67531300fecc3cdccbd4a4a737072a
2026-05-31 23:50:14.326 | INFO     | __main__:<module>:2 - Logging customer ID: faab89791a68dd8987c735e5b1455b68afc6d72b965c17f49b38b88e0a2970ab
2026-05-31 23:50:14.327 | INFO     | __main__:<module>:2 - Logging customer ID: 424cdc376758ef20930e83dd117f73f8be868eef1b50fda6e39e32991b89753f
2026-05-31 23:50:14.327 | INFO     | __main__:<module>:2 - Logging customer ID: 7888dfc9177cb3b8db5e668c8b75b711216f42c8381d917d53dcadb9695a5c3e
2026-05-31 23:50:14.328 | INFO     | __main__:<module>:2 - Logging customer ID: f1f1e73f19a9d7047f4916e4e91a43c79d9efaaa76378c601e6c8c064fce5055
2026-05-31 23:50:14.328 | INFO     | __main__:<module>:2 - Logging customer ID: f3e358b4514621109fc0eee3f5ec2d222d5254c65dcf0a2a43488d94e3bfa444
2026-05-31 23:50:14.329 | INFO     | __main__:<module>:2 - Logging customer ID: d8f09209406c8e0eaa24f22fcf1d97a3591165d62e5c640a40aeb1b08a9fc2f1
2026-05-31 23:50:14.330 | INFO     | __main__:<module>:2 - Logging customer ID: 3c54662258ad905056ef6e443c3b8429ef0f4d0042d65f67927c1635088057fd
2026-05-31 23:50:14.331 | INFO     | __main__:<module>:2 - Logging customer ID: 80d16854f01efd9c4aa896d3684c95e4055e3632138da4409c1f1823791e7408
2026-05-31 23:50:14.332 | INFO     | __main__:<module>:2 - Logging customer ID: a8bbc6fd156a7c275c06b5d48ef5c628f4d625c5c9b2db58e0343284bb311b52

# 🤳🏻 Interaction data

To train our models, we need more than just the transactions DataFrame. We need positive samples that signal whether a customer clicked or bought an item, but we also need negative samples that signal no interactions between a customer and an item.

In [32]:
interaction_df = generate_interaction_data(transactions_df)
interaction_df.shape

Processing customer chunks: 100%|██████████| 1/1 [00:05<00:00,  5.92s/it]

(135640, 5)

The interaction features look as follows:

In [33]:
interaction_df.head()

shape: (5, 5)
┌────────────┬─────────────────────────────────┬────────────┬───────────────────┬─────────────────┐
│ t_dat      ┆ customer_id                     ┆ article_id ┆ interaction_score ┆ prev_article_id │
│ ---        ┆ ---                             ┆ ---        ┆ ---               ┆ ---             │
│ i64        ┆ str                             ┆ str        ┆ i64               ┆ str             │
╞════════════╪═════════════════════════════════╪════════════╪═══════════════════╪═════════════════╡
│ -374400000 ┆ 00b203a32faa3d007dba198ef27c15… ┆ 878604001  ┆ 0                 ┆ START           │
│ -363600000 ┆ 00b203a32faa3d007dba198ef27c15… ┆ 875025002  ┆ 0                 ┆ 878604001       │
│ -360000000 ┆ 00b203a32faa3d007dba198ef27c15… ┆ 875025002  ┆ 0                 ┆ 875025002       │
│ -352800000 ┆ 00b203a32faa3d007dba198ef27c15… ┆ 824118001  ┆ 0                 ┆ 875025002       │
│ -349200000 ┆ 00b203a32faa3d007dba198ef27c15… ┆ 638614001  ┆ 0                 ┆ 824118001       │
└────────────┴─────────────────────────────────┴────────────┴───────────────────┴─────────────────┘

Let's take a look at the interaction score distribution:

In [34]:
interaction_df.group_by("interaction_score").agg(
    pl.count("interaction_score").alias("total_interactions")
)

shape: (3, 2)
┌───────────────────┬────────────────────┐
│ interaction_score ┆ total_interactions │
│ ---               ┆ ---                │
│ i64               ┆ u32                │
╞═══════════════════╪════════════════════╡
│ 0                 ┆ 73832              │
│ 1                 ┆ 38009              │
│ 2                 ┆ 23799              │
└───────────────────┴────────────────────┘

Here is what each score means:
- `0` : No interaction between a customer and an item
- `1` : A customer clicked an item
- `2` : A customer bought an item

# <span style="color:#ff5f27">🪄 Create Hopsworks Feature Groups </span>

A [feature group](https://docs.hopsworks.ai/feature-store-api/latest/generated/feature_group/) can be seen as a collection of conceptually related features.

To create a feature group you need to give it a name and specify a primary key. It is also best practice to provide a description of the contents of the feature group.

#### Customers

We set `online_enabled=True` to enable low-latency access to the data from the inference pipeline for real-time predictions. 

A full list of arguments can be found in the [documentation](https://docs.hopsworks.ai/feature-store-api/latest/generated/api/feature_store_api/#create_feature_group).

In [35]:
logger.info("Uploading 'customers' Feature Group to Hopsworks.")
customers_fg = feature_store.create_customers_feature_group(
    fs, df=customers_df, online_enabled=True
)

logger.info("✅ Uploaded 'customers' Feature Group to Hopsworks!")

2026-05-31 23:51:05.138 | INFO     | __main__:<module>:1 - Uploading 'customers' Feature Group to Hopsworks.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/33047/fs/21731/fg/42034

Uploading Dataframe: 100.00% |██████████| Rows 1000/1000 | Elapsed Time: 00:01 | Remaining Time: 00:00

Launching job: customers_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://eu-west.cloud.hopsworks.ai:443/p/33047/jobs/named/customers_1_offline_fg_materialization/executions
2026-05-31 23:51:31,438 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2026-05-31 23:51:34,704 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2026-05-31 23:53:29,028 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2026-05-31 23:53:29,283 INFO: Waiting for log aggregation to finish.
2026-05-31 23:53:38,274 INFO: Execution finished successfully.

Online data ingestion progress: 100.00% |██████████| Rows 1000/1000
2026-05-31 23:53:44.317 | INFO     | __main__:<module>:6 - ✅ Uploaded 'customers' Feature Group to Hopsworks!

#### Articles

Let's do the same thing for the rest of the data frames.

In [36]:
logger.info("Uploading 'articles' Feature Group to Hopsworks.")
articles_fg = feature_store.create_articles_feature_group(
    fs,
    df=articles_df,
    articles_description_embedding_dim=model.get_sentence_embedding_dimension(),
    online_enabled=True,
)
logger.info("✅ Uploaded 'articles' Feature Group to Hopsworks!")

2026-05-31 23:54:18.651 | INFO     | __main__:<module>:1 - Uploading 'articles' Feature Group to Hopsworks.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/33047/fs/21731/fg/42035

Uploading Dataframe: 100.00% |██████████| Rows 105542/105542 | Elapsed Time: 00:44 | Remaining Time: 00:00

Launching job: articles_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://eu-west.cloud.hopsworks.ai:443/p/33047/jobs/named/articles_1_offline_fg_materialization/executions
2026-05-31 23:55:23,630 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2026-05-31 23:55:26,895 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2026-05-31 23:58:46,164 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2026-05-31 23:58:46,404 INFO: Waiting for log aggregation to finish.
2026-05-31 23:58:58,897 INFO: Execution finished successfully.

Online data ingestion progress: 100.00% |██████████| Rows 105542/105542
2026-05-31 23:58:59.238 | INFO     | __main__:<module>:8 - ✅ Uploaded 'articles' Feature Group to Hopsworks!

####  Transactions

In [37]:
logger.info("Uploading 'transactions' Feature Group to Hopsworks.")
trans_fg = feature_store.create_transactions_feature_group(
    fs=fs, df=transactions_df, online_enabled=True
)
logger.info("✅ Uploaded 'transactions' Feature Group to Hopsworks!")

2026-06-01 00:00:33.603 | INFO     | __main__:<module>:1 - Uploading 'transactions' Feature Group to Hopsworks.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/33047/fs/21731/fg/42036

Uploading Dataframe: 100.00% |██████████| Rows 23799/23799 | Elapsed Time: 00:02 | Remaining Time: 00:00

Launching job: transactions_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://eu-west.cloud.hopsworks.ai:443/p/33047/jobs/named/transactions_1_offline_fg_materialization/executions
2026-06-01 00:00:57,482 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2026-06-01 00:01:00,747 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2026-06-01 00:03:04,695 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2026-06-01 00:03:04,936 INFO: Waiting for log aggregation to finish.
2026-06-01 00:03:17,414 INFO: Execution finished successfully.

Online data ingestion progress: 100.00% |██████████| Rows 23799/23799
2026-06-01 00:03:31.314 | INFO     | __main__:<module>:5 - ✅ Uploaded 'transactions' Feature Group to Hopsworks!

#### Interactions

In [38]:
logger.info("Uploading 'interactions' Feature Group to Hopsworks.")
interactions_fg = feature_store.create_interactions_feature_group(
    fs=fs, df=interaction_df, online_enabled=True
)
logger.info("✅ Uploaded 'interactions' Feature Group to Hopsworks!!")

2026-06-01 00:04:16.700 | INFO     | __main__:<module>:1 - Uploading 'interactions' Feature Group to Hopsworks.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/33047/fs/21731/fg/42037

Uploading Dataframe: 100.00% |██████████| Rows 135640/135640 | Elapsed Time: 00:03 | Remaining Time: 00:00

Launching job: interactions_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://eu-west.cloud.hopsworks.ai:443/p/33047/jobs/named/interactions_1_offline_fg_materialization/executions
2026-06-01 00:04:40,082 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2026-06-01 00:04:43,363 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2026-06-01 00:06:50,634 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2026-06-01 00:06:50,880 INFO: Waiting for log aggregation to finish.
2026-06-01 00:06:59,867 INFO: Execution finished successfully.

Online data ingestion progress: 100.00% |██████████| Rows 135640/135640
2026-06-01 00:07:05.934 | INFO     | __main__:<module>:5 - ✅ Uploaded 'interactions' Feature Group to Hopsworks!!

# Compute ranking dataset

The last step is to compute the ranking dataset used to train the scoring/ranking model from the feature groups we've just created:

In [39]:
ranking_df = compute_ranking_dataset(
    trans_fg,
    articles_fg,
    customers_fg,
)
ranking_df.shape

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (2.11s)
Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (11.71s)
Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (1.13s)
Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (95.05s)

(224136, 15)

The ranking dataset looks as follows:

In [40]:
ranking_df.head(3)

shape: (3, 15)
┌─────────────┬──────┬────────────┬───────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ customer_id ┆ age  ┆ article_id ┆ label ┆ … ┆ index_name  ┆ index_grou ┆ section_na ┆ garment_gr │
│ ---         ┆ ---  ┆ ---        ┆ ---   ┆   ┆ ---         ┆ p_name     ┆ me         ┆ oup_name   │
│ str         ┆ f64  ┆ str        ┆ i32   ┆   ┆ str         ┆ ---        ┆ ---        ┆ ---        │
│             ┆      ┆            ┆       ┆   ┆             ┆ str        ┆ str        ┆ str        │
╞═════════════╪══════╪════════════╪═══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 34d30dcece3 ┆ 64.0 ┆ 839496003  ┆ 1     ┆ … ┆ Ladieswear  ┆ Ladieswear ┆ Womens     ┆ Jersey     │
│ 8ac652e9fd0 ┆      ┆            ┆       ┆   ┆             ┆            ┆ Everyday   ┆ Fancy      │
│ 5285d94d…   ┆      ┆            ┆       ┆   ┆             ┆            ┆ Collection ┆            │
│ 91a30617b9a ┆ 49.0 ┆ 777093001  ┆ 1     ┆ … ┆ Children    ┆ Baby/Child ┆ Young Girl ┆ Dresses/Sk │
│ 5b5ff392777 ┆      ┆            ┆       ┆   ┆ Sizes       ┆ ren        ┆            ┆ irts girls │
│ 9204a176…   ┆      ┆            ┆       ┆   ┆ 134-170     ┆            ┆            ┆            │
│ 23eeb5e9595 ┆ 25.0 ┆ 875719003  ┆ 1     ┆ … ┆ Divided     ┆ Divided    ┆ Divided    ┆ Trousers   │
│ c9409031f21 ┆      ┆            ┆       ┆   ┆             ┆            ┆ Selected   ┆            │
│ a9c01fa3…   ┆      ┆            ┆       ┆   ┆             ┆            ┆            ┆            │
└─────────────┴──────┴────────────┴───────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [41]:
ranking_df.get_column("label").value_counts()

shape: (2, 2)
┌───────┬────────┐
│ label ┆ count  │
│ ---   ┆ ---    │
│ i32   ┆ u32    │
╞═══════╪════════╡
│ 0     ┆ 203760 │
│ 1     ┆ 20376  │
└───────┴────────┘

As the ranking dataset was computed based on articles, customers, and transactions Hopsworks Feature Groups, we can reflect this lineage in the ranking Feature Group.

In [42]:
logger.info("Uploading 'ranking' Feature Group to Hopsworks.")
rank_fg = feature_store.create_ranking_feature_group(
    fs,
    df=ranking_df,
    parents=[articles_fg, customers_fg, trans_fg],
    online_enabled=False
)
logger.info("✅ Uploaded 'ranking' Feature Group to Hopsworks!!")

2026-06-01 00:10:27.429 | INFO     | __main__:<module>:1 - Uploading 'ranking' Feature Group to Hopsworks.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/33047/fs/21731/fg/42038

Uploading Dataframe: 100.00% |██████████| Rows 224136/224136 | Elapsed Time: 00:04 | Remaining Time: 00:00

Launching job: ranking_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://eu-west.cloud.hopsworks.ai:443/p/33047/jobs/named/ranking_1_offline_fg_materialization/executions
2026-06-01 00:10:50,763 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2026-06-01 00:10:54,030 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2026-06-01 00:13:17,755 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2026-06-01 00:13:18,000 INFO: Waiting for log aggregation to finish.
2026-06-01 00:13:27,012 INFO: Execution finished successfully.

2026-06-01 00:13:45.263 | INFO     | __main__:<module>:8 - ✅ Uploaded 'ranking' Feature Group to Hopsworks!!

## <span style="color:#ff5f27"> Inspecting the Feature Groups in Hopsworks UI </span>

View results in [Hopsworks Serverless](https://rebrand.ly/serverless-github): **Feature Store → Feature Groups**

---

In [44]:
notebook_end_time = time.time()
notebook_execution_time = notebook_end_time - notebook_start_time

logger.info(
    f"⌛️ Notebook Execution time: {notebook_execution_time:.2f} seconds ~ {notebook_execution_time / 60:.2f} minutes"
)

2026-06-01 00:14:41.057 | INFO     | __main__:<module>:4 - ⌛️ Notebook Execution time: 13792.22 seconds ~ 229.87 minutes

# <span style="color:#ff5f27">→ Next Steps </span>

In the next notebook you'll train the retrieval model and register it to the Hopsworks model registry.